# Stage 1: 
FROM node:20.18.0 AS build-stage

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .
RUN npm run build --prod

# Stage 2: 
FROM nginx:stable-alpine
COPY default.conf /etc/nginx/conf.d/
COPY --from=build-stage /app/dist/* /usr/share/nginx/html

